id: I76B64637
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:35:33.113202
last_modified: 2023-02-10 00:35:33.113318
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: bo
bases:
  0B15:
    base_file: 0B15.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
